// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI tooling (studio, migrate, db push) needs a direct Postgres connection,
    // not the Accelerate proxy URL used by the app's runtime client.
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
